#!/bin/bash

#copy and paste ip ranges with the CIDR straight into the `iprange` variable
iprange=(<define IP ranges here>)

#alternatively, you can use the contents of a file to define the iprange variable
#for example, iprange=$(cat <absolute file path>/<file name>)

#for loop to ping each IP defined under the variable
for ip in ${iprange[@]}
do
        fping -g $ip
done
